# Generated by Django 5.0.4 on 2024-05-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='cities.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_images', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Изображение Ресторана',
                'verbose_name_plural': 'Изображения Ресторанов',
            },
        ),
    ]
