# Generated by Django 5.0.4 on 2024-05-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_dish', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dish_images/')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_images', to='dishes.dish')),
            ],
            options={
                'verbose_name': 'Изображение Блюда',
                'verbose_name_plural': 'Изображение Блюд',
            },
        ),
    ]
