# Generated by Django 5.0.4 on 2024-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
