# Generated by Django 5.0.4 on 2024-05-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='descripton',
            new_name='description',
        ),
    ]
